version: "3.7"

services:
  mysql:
    image: mysql
    restart: always
    volumes:
      - todo-mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: mohammad79
      MYSQL_DATABASE: digiBot
    ports:
    - 3306:3306

  app:
    image: digibot
    restart: always
    environment:
      DB_HOST: mysql
      DB_PASSWORD: mohammad79


volumes:
  todo-mysql-data:
