version: "3.7"

services:
  mysql:
    image: mysql
    restart: always
    volumes:
      - mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: $DB_PASSWORD
      MYSQL_DATABASE: $DB_NAME
    ports:
      - "3306:3306"

  app:
    image: digibot
    restart: always
    environment:
      DB_HOST: $DB_HOST
      DB_USERNAME: $DB_USERNAME
      DB_PASSWORD: $DB_PASSWORD
      DB_NAME: $DB_NAME
      BOT_TOKEN: $BOT_TOKEN


volumes:
  mysql:
